### ISSUE TITLE
Configuration question  

### ISSUE THREAD

**Issue by ssisson** [metadaddy-sfdc/Forcecraft#14]
This is probably pilot error, but tonight I spent some time trying to get this running and I got pretty close. I used the instructions on the repo, and when using Forge 1.7.2, I kept getting an error when I'd attempt to launch using the Forge profile:

java.io.IOException: Error=13 Permission Denied

I figured I could change this by changing the profile to downgrade and look at a 1.7 JRE, but that didn't seem to work for me (I tried to make my JRE directory accessible, but I'm not sure I succeeded) 

Being oh-so-clever, I tried upgrading to Forge 1.7.10. That worked great-- I got past the Permission Denied error-- the mod installed, all looked good, but when I went to launch my cool new world, it crashed with an error: 

no opengl context found in the current thread 

So, while I didn't expect that to work because 1.7.10 is not supported, I figured I'd ask to see what my best course of action is here-- do I need to downgrade my JRE more aggressively, or am I doing something obviously wrong when I'm configuring?   

Thanks!

**Comment by metadaddy-sfdc** [comment]
IO error 13? That's a weird one - like it's trying to read or write a file, but it doesn't have perms. Can you post the call stack? What are you running on - Mac? Windows? Linux? Does Minecraft + Forge start ok without the Forcecraft mod?

**Comment by ssisson** [comment]
Thanks, yeah, I'm on a Mac (Mavericks). Minecraft and Forge both start ok when I don't have the mod installed. In fact, with the 1.7.10 version of Forge, I can get all the way in, it just fails when I launch the world itself. 

I will try downgrading my JRE and going back down to Forge 1.7.2 to see if that does the trick.

**Comment by metadaddy-sfdc** [comment]
Yeah - I just tried running it on my Mac with Java 8 and got a different error:

    [21:41:12] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
	[21:41:12] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
	[21:41:12] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
	[21:41:12] [main/INFO]: Forge Mod Loader version 7.2.156.1060 for Minecraft 1.7.2 loading
	[21:41:12] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_40, running on Mac OS X:x86_64:10.10.5, installed at /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre
	[21:41:12] [main/INFO]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
	[21:41:12] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
	[21:41:12] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
	[21:41:12] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
	[21:41:12] [main/ERROR]: Unable to launch
	java.util.ConcurrentModificationException
		at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_40]
		at java.util.ArrayList$Itr.remove(ArrayList.java:865) ~[?:1.8.0_40]
		at net.minecraft.launchwrapper.Launch.launch(Launch.java:117) [launchwrapper-1.9.jar:?]
		at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]

This is a known issue with Java 8 and Forge 1.7.2. I fixed it by grabbing the [patched class file](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2206446-forge-1-6-4-1-7-2-java-8-compatibility-patch), making it into a JAR ([download it from here](https://drive.google.com/file/d/0B7E3_kUjDsZXWlpoOVV0c1ZkeTQ/view?usp=sharing)) and adding to the top of the build path. See if it works for you...

**Comment by metadaddy-sfdc** [comment]
Closing this since it's been a couple of months with no reply.

**Comment by douglasrmholmes** [comment]
@metadaddy Could you provide guidance regarding the best way to get Forcecraft up and running?
Specifically, do you recommend using an older version of Java or [patching forge directly](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2206446-forge-1-6-4-1-7-2-java-8-compatibility-patch)?
